### ISSUE TITLE
Problems during training

### ISSUE THREAD

**Issue by Millielele** [mikemikezhu/FedILC#1]
Thanks for your excellent work!
When i run main.py, i encounter this problem:
XIO:  fatal IO error 25 (Inappropriate ioctl for device) on X server "localhost:10.0"
      after 397 requests (397 known processed) with 4 events remaining.

The cause of the issue may be the matplotlib, how to solve that?

**Comment by mikemikezhu** [comment]
> Thanks for your excellent work! When i run main.py, i encounter this problem: XIO: fatal IO error 25 (Inappropriate ioctl for device) on X server "localhost:10.0" after 397 requests (397 known processed) with 4 events remaining.
> 
> The cause of the issue may be the matplotlib, how to solve that?

Hi @Millielele Thank you so much for your feedback!
As far as I checked, "fatal IO error 25 (Inappropriate ioctl for device)" might be caused by ""

**Comment by mikemikezhu** [comment]
> Thanks for your excellent work! When i run main.py, i encounter this problem: XIO: fatal IO error 25 (Inappropriate ioctl for device) on X server "localhost:10.0" after 397 requests (397 known processed) with 4 events remaining.
> 
> The cause of the issue may be the matplotlib, how to solve that?

Hi! As far as I have checked, this issue might be engendered by connecting to the SSH (See: https://stackoverflow.com/questions/43047175/inappropriate-ioctl-for-device-when-trying-to-ssh), and doesn't seem to be related to our software. Would you mind double check that you are using python virtual environment and installed all the required packages?

**Comment by Millielele** [comment]
Thanks a lot
